In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

In [6]:
dflm = pd.read_csv("D:/MODELISATION/MASG2/DATA SCIENCE/INOHA-DataScience-M2/donnees_mpox_RDC_3000.csv") 
dflm

,ID,Semaine,Province,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Saison,Population_Risque,Taux_Positivite_pct
0,OBS_00001,1,Mongala,206,24.4,0.480,64,39,31.8,150,22,1,4,29,Pluie,3478,19.33
1,OBS_00002,2,Kinshasa,56,23.7,0.474,74,107,24.9,300,5,1,6,42,Seche,3713,14.00
2,OBS_00003,3,Kinshasa,59,25.2,0.333,62,140,53.9,310,16,0,8,20,Seche,4833,6.45
3,OBS_00004,4,Mai-Ndombe,396,24.1,0.354,68,97,25.9,210,4,0,10,82,Pluie,3777,39.05
4,OBS_00005,5,Kasaï,127,19.8,0.303,61,86,30.3,260,24,1,6,24,Pluie,9396,9.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,OBS_02996,2996,Kongo Central,271,31.6,0.534,88,57,22.4,220,33,1,7,125,Pluie,3166,56.82
2996,OBS_02997,2997,Sud-Ubangi,88,24.6,0.262,95,47,34.1,370,7,1,6,70,Seche,6099,18.92
2997,OBS_02998,2998,Bas-Uele,268,25.6,0.720,58,18,41.9,190,23,0,2,36,Pluie,5475,18.95
2998,OBS_02999,2999,Haut-Uele,211,24.9,0.196,77,28,10.6,370,2,0,2,160,Pluie,4813,43.24
2999,OBS_03000,3000,Sud-Kivu,126,27.0,0.632,57,51,74.3,240,46,1,2,10,Pluie,8049,4.17

In [7]:
dflm.describe()

,Semaine,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Population_Risque,Taux_Positivite_pct
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,157.779667,24.980367,0.451182,71.571667,119.100333,31.843967,286.143333,15.558333,0.40000,5.018000,79.603333,5471.297667,27.041943
std,866.169729,101.958774,3.832510,0.157799,11.625285,95.218460,14.079517,88.256194,15.139386,0.48998,1.954213,70.119799,2636.188129,20.156959
min,1.000000,2.000000,18.000000,0.103000,40.000000,5.000000,5.600000,90.000000,1.000000,0.00000,1.000000,0.000000,1001.000000,0.000000
25%,750.750000,77.000000,22.300000,0.331000,64.000000,48.000000,20.800000,220.000000,5.000000,0.00000,4.000000,29.000000,3127.000000,11.430000
50%,1500.500000,136.000000,24.900000,0.452000,71.500000,94.000000,30.400000,280.000000,11.000000,0.00000,5.000000,57.000000,5514.500000,21.455000
75%,2250.250000,221.000000,27.600000,0.576000,80.000000,163.000000,41.525000,340.000000,22.000000,1.00000,6.000000,109.000000,7819.250000,38.070000
max,3000.000000,400.000000,34.000000,0.795000,95.000000,500.000000,77.800000,800.000000,142.000000,1.00000,10.000000,479.000000,9997.000000,95.000000

In [8]:
count = dflm.isnull().sum()
print(count)

ID                          0
Semaine                     0
Province                    0
Pluviometrie_mm             0
Temperature_C               0
NDVI                        0
Humidite_pct                0
Densite_Population          0
Couverture_Vaccinale_pct    0
Tests_Realises              0
Distance_Centre_Sante_km    0
Reservoirs_Animaux          0
Mobilite_Humaine            0
Cas_Confirmes               0
Saison                      0
Population_Risque           0
Taux_Positivite_pct         0
dtype: int64

In [9]:
missing_data = count/len(dflm)*100
print(missing_data)

ID                          0.0
Semaine                     0.0
Province                    0.0
Pluviometrie_mm             0.0
Temperature_C               0.0
NDVI                        0.0
Humidite_pct                0.0
Densite_Population          0.0
Couverture_Vaccinale_pct    0.0
Tests_Realises              0.0
Distance_Centre_Sante_km    0.0
Reservoirs_Animaux          0.0
Mobilite_Humaine            0.0
Cas_Confirmes               0.0
Saison                      0.0
Population_Risque           0.0
Taux_Positivite_pct         0.0
dtype: float64

In [10]:
dflm = dflm.dropna()
dflm.shape

(3000, 17)

In [11]:
dflm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        3000 non-null   object
 1   Semaine                   3000 non-null   int64
 2   Province                  3000 non-null   object
 3   Pluviometrie_mm           3000 non-null   int64
 4   Temperature_C             3000 non-null   float64
 5   NDVI                      3000 non-null   float64
 6   Humidite_pct              3000 non-null   int64
 7   Densite_Population        3000 non-null   int64
 8   Couverture_Vaccinale_pct  3000 non-null   float64
 9   Tests_Realises            3000 non-null   int64
 10  Distance_Centre_Sante_km  3000 non-null   int64
 11  Reservoirs_Animaux        3000 non-null   int64
 12  Mobilite_Humaine          3000 non-null   int64
 13  Cas_Confirmes             3000 non-null   int64
 14  Saison                    3000 non-null   object
 15  Population_Risque         3000 non-null   int64
 16  Taux_Positivite_pct       3000 non-null   float64
dtypes: float64(4), int64(10), object(3)
memory usage: 398.6+ KB

In [12]:
dflm.columns

Index(['ID', 'Semaine', 'Province', 'Pluviometrie_mm', 'Temperature_C', 'NDVI',
       'Humidite_pct', 'Densite_Population', 'Couverture_Vaccinale_pct',
       'Tests_Realises', 'Distance_Centre_Sante_km', 'Reservoirs_Animaux',
       'Mobilite_Humaine', 'Cas_Confirmes', 'Saison', 'Population_Risque',
       'Taux_Positivite_pct'],
      dtype='object')

In [13]:
df_txt = dflm.select_dtypes(include=["object"])
df_txt

             ID       Province Saison
0     OBS_00001        Mongala  Pluie
1     OBS_00002       Kinshasa  Seche
2     OBS_00003       Kinshasa  Seche
3     OBS_00004     Mai-Ndombe  Pluie
4     OBS_00005          Kasaï  Pluie
...         ...            ...    ...
2995  OBS_02996  Kongo Central  Pluie
2996  OBS_02997     Sud-Ubangi  Seche
2997  OBS_02998       Bas-Uele  Pluie
2998  OBS_02999      Haut-Uele  Pluie
2999  OBS_03000       Sud-Kivu  Pluie

[3000 rows x 3 columns]

In [14]:
df_txt.columns

Index(['ID', 'Province', 'Saison'], dtype='object')

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

columns = ['ID', 'Semaine', 'Province', 'Pluviometrie_mm', 'Temperature_C', 'NDVI',
       'Humidite_pct', 'Densite_Population', 'Couverture_Vaccinale_pct',
       'Tests_Realises', 'Distance_Centre_Sante_km', 'Reservoirs_Animaux',
       'Mobilite_Humaine', 'Cas_Confirmes', 'Saison', 'Population_Risque',
       'Taux_Positivite_pct']

for i in columns :
  dflm[i] = le.fit_transform(dflm[i])

In [16]:
dflm

,ID,Semaine,Province,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Saison,Population_Risque,Taux_Positivite_pct
0,0,0,16,204,64,353,24,34,255,6,21,1,3,29,0,735,616
1,1,1,8,54,57,347,34,102,186,21,4,1,5,42,1,806,426
2,2,2,8,57,72,206,22,135,473,22,15,0,7,20,1,1117,168
3,3,3,14,378,61,227,28,92,196,12,3,0,9,82,0,830,1139
4,4,4,5,125,18,176,21,81,240,17,23,1,5,24,0,2396,262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,2995,9,269,136,406,48,52,161,13,32,1,6,125,0,642,1437
2996,2996,2996,21,86,66,135,55,42,278,28,6,1,5,70,1,1452,601
2997,2997,2997,0,266,76,589,18,13,356,10,22,0,1,36,0,1271,603
2998,2998,2998,3,209,69,70,37,23,43,28,1,0,1,160,0,1111,1221
2999,2999,2999,20,124,90,504,17,46,599,15,45,1,1,10,0,2007,80

In [17]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
dflm_min = minmax.fit_transform(dflm)

dflm_scaler = pd.DataFrame(dflm_min, columns =dflm.columns)

dflm_scaler

,ID,Semaine,Province,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Saison,Population_Risque,Taux_Positivite_pct
0,0.000000,0.000000,0.64,0.536842,0.40000,0.547287,0.436364,0.085642,0.423588,0.111111,0.244186,1.0,0.333333,0.091483,0.0,0.285326,0.359184
1,0.000333,0.000333,0.32,0.142105,0.35625,0.537984,0.618182,0.256927,0.308970,0.388889,0.046512,1.0,0.555556,0.132492,1.0,0.312888,0.248397
2,0.000667,0.000667,0.32,0.150000,0.45000,0.319380,0.400000,0.340050,0.785714,0.407407,0.174419,0.0,0.777778,0.063091,1.0,0.433618,0.097959
3,0.001000,0.001000,0.56,0.994737,0.38125,0.351938,0.509091,0.231738,0.325581,0.222222,0.034884,0.0,1.000000,0.258675,0.0,0.322205,0.664140
4,0.001334,0.001334,0.20,0.328947,0.11250,0.272868,0.381818,0.204030,0.398671,0.314815,0.267442,1.0,0.555556,0.075710,0.0,0.930124,0.152770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.998666,0.998666,0.36,0.707895,0.85000,0.629457,0.872727,0.130982,0.267442,0.240741,0.372093,1.0,0.666667,0.394322,0.0,0.249224,0.837901
2996,0.999000,0.999000,0.84,0.226316,0.41250,0.209302,1.000000,0.105793,0.461794,0.518519,0.069767,1.0,0.555556,0.220820,1.0,0.563665,0.350437
2997,0.999333,0.999333,0.00,0.700000,0.47500,0.913178,0.327273,0.032746,0.591362,0.185185,0.255814,0.0,0.111111,0.113565,0.0,0.493401,0.351603
2998,0.999667,0.999667,0.12,0.550000,0.43125,0.108527,0.672727,0.057935,0.071429,0.518519,0.011628,0.0,0.111111,0.504732,0.0,0.431289,0.711953
2999,1.000000,1.000000,0.80,0.326316,0.56250,0.781395,0.309091,0.115869,0.995017,0.277778,0.523256,1.0,0.111111,0.031546,0.0,0.779115,0.046647

In [18]:
dflm_scaler.columns

Index(['ID', 'Semaine', 'Province', 'Pluviometrie_mm', 'Temperature_C', 'NDVI',
       'Humidite_pct', 'Densite_Population', 'Couverture_Vaccinale_pct',
       'Tests_Realises', 'Distance_Centre_Sante_km', 'Reservoirs_Animaux',
       'Mobilite_Humaine', 'Cas_Confirmes', 'Saison', 'Population_Risque',
       'Taux_Positivite_pct'],
      dtype='object')

In [36]:
X = dflm_scaler.drop(
    ['Cas_Confirmes', 'ID'],
    axis=1
)

y = dflm_scaler['Cas_Confirmes']

In [37]:
X

,Semaine,Province,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Saison,Population_Risque,Taux_Positivite_pct
0,0.000000,0.64,0.536842,0.40000,0.547287,0.436364,0.085642,0.423588,0.111111,0.244186,1.0,0.333333,0.0,0.285326,0.359184
1,0.000333,0.32,0.142105,0.35625,0.537984,0.618182,0.256927,0.308970,0.388889,0.046512,1.0,0.555556,1.0,0.312888,0.248397
2,0.000667,0.32,0.150000,0.45000,0.319380,0.400000,0.340050,0.785714,0.407407,0.174419,0.0,0.777778,1.0,0.433618,0.097959
3,0.001000,0.56,0.994737,0.38125,0.351938,0.509091,0.231738,0.325581,0.222222,0.034884,0.0,1.000000,0.0,0.322205,0.664140
4,0.001334,0.20,0.328947,0.11250,0.272868,0.381818,0.204030,0.398671,0.314815,0.267442,1.0,0.555556,0.0,0.930124,0.152770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.998666,0.36,0.707895,0.85000,0.629457,0.872727,0.130982,0.267442,0.240741,0.372093,1.0,0.666667,0.0,0.249224,0.837901
2996,0.999000,0.84,0.226316,0.41250,0.209302,1.000000,0.105793,0.461794,0.518519,0.069767,1.0,0.555556,1.0,0.563665,0.350437
2997,0.999333,0.00,0.700000,0.47500,0.913178,0.327273,0.032746,0.591362,0.185185,0.255814,0.0,0.111111,0.0,0.493401,0.351603
2998,0.999667,0.12,0.550000,0.43125,0.108527,0.672727,0.057935,0.071429,0.518519,0.011628,0.0,0.111111,0.0,0.431289,0.711953
2999,1.000000,0.80,0.326316,0.56250,0.781395,0.309091,0.115869,0.995017,0.277778,0.523256,1.0,0.111111,0.0,0.779115,0.046647

In [38]:
y

0       0.091483
1       0.132492
2       0.063091
3       0.258675
4       0.075710
          ...
2995    0.394322
2996    0.220820
2997    0.113565
2998    0.504732
2999    0.031546
Name: Cas_Confirmes, Length: 3000, dtype: float64

In [40]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=20)

In [41]:
model_LRM = LinearRegression()
model_LRM.fit(x_train, y_train)

LinearRegression()

In [42]:
bo = model_LRM.intercept_
bo

np.float64(-0.2364813268016706)

In [43]:
coef = model_LRM.coef_
coef

array([-4.46299602e-03,  4.64008933e-03,  9.74173783e-02,  1.34668175e-02,
        1.15606021e-02, -4.60902596e-04,  2.34651879e-02, -1.97439283e-02,
        4.63776623e-01,  4.34008137e-03, -2.85122344e-03,  5.49707633e-04,
        3.35976491e-02,  1.32656213e-03,  5.87187601e-01])

In [45]:
y_pred = model_LRM.predict(x_test)
y_pred

array([ 0.1668744 ,  0.28758766,  0.47883036,  0.14072172,  0.17774573,
        0.02208367, -0.05984282, -0.04553977,  0.57170253, -0.00517298,
        0.13421876,  0.5656518 ,  0.0010133 ,  0.47749542,  0.05952553,
        0.12910098,  0.46793985,  0.1040657 ,  0.08429158, -0.03409542,
        0.07213919,  0.37971561,  0.15775348,  0.18170823,  0.70240479,
        0.06759171,  0.21063871,  0.10039945,  0.12789555,  0.10351208,
        0.26955998,  0.0189532 ,  0.2468238 , -0.04311544,  0.03818262,
        0.23669794,  0.21988746,  0.51861158,  0.34748239,  0.01506027,
        0.0459523 ,  0.47197273,  0.09291185,  0.04291992,  0.31566999,
        0.28014927,  0.33979969,  0.47401737,  0.24391809,  0.01779357,
       -0.03032924,  0.12839732, -0.06570027,  0.22678358,  0.09001864,
        0.16095185,  0.09100472,  0.41018116,  0.1019136 ,  0.26047512,
        0.14563216,  0.26243491,  0.26942294,  0.04303446,  0.28614999,
        0.08001567,  0.18793187, -0.07058905,  0.17764948,  0.15055874,
       -0.02458965,  0.10801773,  0.32179022,  0.02896441,  0.41346546,
        0.3610168 ,  0.18468811,  0.24453123,  0.16051789,  0.27615199,
        0.27221695,  0.70956797,  0.75047831,  0.25429999,  0.55670946,
        0.30111792, -0.05150123,  0.54997187,  0.17921809,  0.59384252,
        0.18511281,  0.01366068,  0.32038058,  0.34150806,  0.27960219,
        0.74686943,  0.28111589,  0.17515134,  0.32536621,  0.45093067,
       -0.00196411,  0.46735742,  0.20853681,  0.4121159 ,  0.13098089,
        0.28752974,  0.18904115,  0.31956008,  0.38020586,  0.19464148,
        0.0983219 ,  0.51987038,  0.29930611,  0.5384999 ,  0.23660606,
        0.12128296,  0.53961359,  0.44638283,  0.2148411 ,  0.21393271,
        0.45815069,  0.47615802,  0.34737309,  0.22049955,  0.26337633,
        0.73090986,  0.20833323,  0.53207218,  0.24351147,  0.35588807,
        0.58275594,  0.37247585,  0.53072805,  0.59593041,  0.38072208,
        0.42737234,  0.37857319,  0.30543054,  0.59512132,  0.48757397,
        0.16771021,  0.25970738,  0.33224039,  0.65905182,  0.4000477 ,
        0.28529661,  0.02447594, -0.09547763,  0.56623844,  0.12929484,
        0.37872538,  0.12108918,  0.55638346,  0.1835791 ,  0.37240816,
        0.3666386 ,  0.11444343, -0.01662989,  0.52952924, -0.04603408,
        0.1579993 ,  0.30827765, -0.06817433,  0.02886678,  0.40663947,
        0.25356037,  0.14431258,  0.70963412,  0.09253846,  0.47113808,
        0.4436965 ,  0.7033432 ,  0.00253364,  0.43954544,  0.50939238,
        0.16291012,  0.12899905,  0.20687105,  0.41531083,  0.1812546 ,
        0.08541911,  0.10015627,  0.17216195,  0.27627576, -0.08673591,
       -0.05153693,  0.57556314,  0.12745618,  0.07911786,  0.03969847,
        0.1810845 ,  0.34416511,  0.22229195,  0.62019493,  0.2236164 ,
        0.76274354,  0.55565411,  0.18659357,  0.19308838,  0.40483551,
        0.78746665,  0.20128779,  0.24118613,  0.38923259,  0.23392649,
        0.18281085,  0.32670148,  0.47360523, -0.00261976,  0.02467305,
        0.59376897,  0.61316099,  0.33448111,  0.0475053 ,  0.06434157,
        0.24922198,  0.74634376,  0.13840869,  0.15721157,  0.12052368,
        0.45995687,  0.60754097,  0.17552753,  0.02086683,  0.16733345,
        0.41833106,  0.10334652,  0.50825388,  0.0700815 ,  0.22072234,
        0.41726789,  0.2162249 ,  0.22208604,  0.31265149,  0.59370262,
        0.63337198,  0.20047788,  0.5089596 ,  0.32853836,  0.29716805,
        0.06313895,  0.52205616,  0.11368952,  0.0439169 , -0.03505914,
        0.4789688 ,  0.77658839,  0.41928887,  0.11007907,  0.39055256,
        0.48098482,  0.53275073,  0.13711438,  0.04264312,  0.14354826,
        0.02107568,  0.0336831 ,  0.21693759, -0.10613463,  0.17335325,
        0.26920129,  0.0251499 ,  0.25927067,  0.00112758,  0.11919507,
        0.71001201,  0.40661048,  0.25483773,  0.06735677,  0.15581991,
        0.42006655,  0.09178935,  0.44530198,  0.21036751,  0.64373707,
        0.32988083,  0.52542922,  0.12052096,  0.19692695,  0.53383902,
        0.49006358,  0.27867329,  0.02711857,  0.15495317,  0.32486345,
        0.13576609,  0.43453288,  0.03345273,  0.15098479,  0.21029105,
       -0.04638627,  0.36701184,  0.24783196,  0.00540393,  0.34432128,
        0.24473471,  0.21942448, -0.01510053,  0.44899571,  0.54415238])

In [46]:
print("MSE",mean_squared_error(y_test, y_pred))
print("MAE",mean_absolute_error(y_test, y_pred))
#print("RMSE",math.sqrt(mean_squared_error(y_test, y_pred)))
print("R2", r2_score(y_test, y_pred) )

MSE 0.004277552343065908
MAE 0.04926305329189968
R2 0.9167433934969922

INTERPRETATION
MSE:suggère que les prédictions restent proches des observations réelles.
MAE:les prédictions du modèle s'écartent de la vraie valeur de Cas_Confirmes de 0,049 unité
R2: 91,67 % de la variabilité des cas confirmés est expliquée par les variables introduites dans le modèle.