Le score R2, également connu sous le nom de coefficient de détermination, est une mesure statistique qui représente la proportion de la variance de la variable dépendante ('Mobilite_Humaine')
qui peut être prédite à partir de la variable indépendante ('Cas_Confirmes').

Dans notre contexte actuel, un score R2 de 0,342 signifie qu'environ 34,2 % de la variation de l'Exam_Score peut être expliquée par l'Attendance. Les 65,8 % restants de la variance sont dus à d'autres facteurs non inclus dans notre modèle de régression linéaire simple ou à une variabilité aléatoire.

**Un peu plus en Deep**

* **Score R2 proche de 1 (ou 100 %)** : Indique que le modèle explique presque toute la variabilité de la variable dépendante autour de sa moyenne. Cela signifie que le modèle s'adapte très bien aux données.

*  **Score R2 proche de 0**: Indique que le modèle explique très peu de la variabilité de la variable dépendante. Cela suggère que le modèle est mal adapté aux données, ou que la variable indépendante ne prédit pas fortement la variable dépendante.

Dans notre cas, un **score R2 de 0,342** suggère que, bien que **l'Attendance** ait un certain pouvoir explicatif sur **l'Exam_Score**, il existe probablement d'autres facteurs significatifs influençant l'Exam_Score qui ne sont pas capturés par ce modèle simple.

## **1. Régression Linéaire Multiple**

**Quand l'utiliser ?** Lorsque vous avez plusieurs variables explicatives et que vous supposez que leur impact est additif.
- **Pourquoi ?** Très facile à interpréter. On sait exactement comment chaque variable influence le résultat.
- **Mathématiques** : On cherche à minimiser la Somme des Carrés des Résidus (RSS).$$y = \beta_0 + \beta_1x_1 + \beta_2x_2 + ... + \beta_nx_n + \epsilon$$

In [32]:
dflm = pd.read_csv("E:/MES ETUDES/MASTER/M2 MASG/PROJET_DATA_SCIENCE/INOHA-DataScience-M2/donnees_mpox_RDC_3000.csv")
dflm

,ID,Semaine,Province,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Saison,Population_Risque,Taux_Positivite_pct
0,OBS_00001,1,Mongala,206,24.4,0.480,64,39,31.8,150,22,1,4,29,Pluie,3478,19.33
1,OBS_00002,2,Kinshasa,56,23.7,0.474,74,107,24.9,300,5,1,6,42,Seche,3713,14.00
2,OBS_00003,3,Kinshasa,59,25.2,0.333,62,140,53.9,310,16,0,8,20,Seche,4833,6.45
3,OBS_00004,4,Mai-Ndombe,396,24.1,0.354,68,97,25.9,210,4,0,10,82,Pluie,3777,39.05
4,OBS_00005,5,Kasaï,127,19.8,0.303,61,86,30.3,260,24,1,6,24,Pluie,9396,9.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,OBS_02996,2996,Kongo Central,271,31.6,0.534,88,57,22.4,220,33,1,7,125,Pluie,3166,56.82
2996,OBS_02997,2997,Sud-Ubangi,88,24.6,0.262,95,47,34.1,370,7,1,6,70,Seche,6099,18.92
2997,OBS_02998,2998,Bas-Uele,268,25.6,0.720,58,18,41.9,190,23,0,2,36,Pluie,5475,18.95
2998,OBS_02999,2999,Haut-Uele,211,24.9,0.196,77,28,10.6,370,2,0,2,160,Pluie,4813,43.24
2999,OBS_03000,3000,Sud-Kivu,126,27.0,0.632,57,51,74.3,240,46,1,2,10,Pluie,8049,4.17

In [33]:
dflm.describe()

,Semaine,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Population_Risque,Taux_Positivite_pct
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,157.779667,24.980367,0.451182,71.571667,119.100333,31.843967,286.143333,15.558333,0.40000,5.018000,79.603333,5471.297667,27.041943
std,866.169729,101.958774,3.832510,0.157799,11.625285,95.218460,14.079517,88.256194,15.139386,0.48998,1.954213,70.119799,2636.188129,20.156959
min,1.000000,2.000000,18.000000,0.103000,40.000000,5.000000,5.600000,90.000000,1.000000,0.00000,1.000000,0.000000,1001.000000,0.000000
25%,750.750000,77.000000,22.300000,0.331000,64.000000,48.000000,20.800000,220.000000,5.000000,0.00000,4.000000,29.000000,3127.000000,11.430000
50%,1500.500000,136.000000,24.900000,0.452000,71.500000,94.000000,30.400000,280.000000,11.000000,0.00000,5.000000,57.000000,5514.500000,21.455000
75%,2250.250000,221.000000,27.600000,0.576000,80.000000,163.000000,41.525000,340.000000,22.000000,1.00000,6.000000,109.000000,7819.250000,38.070000
max,3000.000000,400.000000,34.000000,0.795000,95.000000,500.000000,77.800000,800.000000,142.000000,1.00000,10.000000,479.000000,9997.000000,95.000000

In [34]:
dflm.isnull().sum()

ID                          0
Semaine                     0
Province                    0
Pluviometrie_mm             0
Temperature_C               0
NDVI                        0
Humidite_pct                0
Densite_Population          0
Couverture_Vaccinale_pct    0
Tests_Realises              0
Distance_Centre_Sante_km    0
Reservoirs_Animaux          0
Mobilite_Humaine            0
Cas_Confirmes               0
Saison                      0
Population_Risque           0
Taux_Positivite_pct         0
dtype: int64

In [35]:
count = dflm.isnull().sum()
print(count)

ID                          0
Semaine                     0
Province                    0
Pluviometrie_mm             0
Temperature_C               0
NDVI                        0
Humidite_pct                0
Densite_Population          0
Couverture_Vaccinale_pct    0
Tests_Realises              0
Distance_Centre_Sante_km    0
Reservoirs_Animaux          0
Mobilite_Humaine            0
Cas_Confirmes               0
Saison                      0
Population_Risque           0
Taux_Positivite_pct         0
dtype: int64

In [36]:
missing_data = count/len(dflm)*100
print(missing_data)

ID                          0.0
Semaine                     0.0
Province                    0.0
Pluviometrie_mm             0.0
Temperature_C               0.0
NDVI                        0.0
Humidite_pct                0.0
Densite_Population          0.0
Couverture_Vaccinale_pct    0.0
Tests_Realises              0.0
Distance_Centre_Sante_km    0.0
Reservoirs_Animaux          0.0
Mobilite_Humaine            0.0
Cas_Confirmes               0.0
Saison                      0.0
Population_Risque           0.0
Taux_Positivite_pct         0.0
dtype: float64

In [37]:
dflm = dflm.dropna()
dflm.shape

(3000, 17)

In [38]:
dflm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        3000 non-null   object
 1   Semaine                   3000 non-null   int64
 2   Province                  3000 non-null   object
 3   Pluviometrie_mm           3000 non-null   int64
 4   Temperature_C             3000 non-null   float64
 5   NDVI                      3000 non-null   float64
 6   Humidite_pct              3000 non-null   int64
 7   Densite_Population        3000 non-null   int64
 8   Couverture_Vaccinale_pct  3000 non-null   float64
 9   Tests_Realises            3000 non-null   int64
 10  Distance_Centre_Sante_km  3000 non-null   int64
 11  Reservoirs_Animaux        3000 non-null   int64
 12  Mobilite_Humaine          3000 non-null   int64
 13  Cas_Confirmes             3000 non-null   int64
 14  Saison                    3000 non-null   object
 15  Population_Risque         3000 non-null   int64
 16  Taux_Positivite_pct       3000 non-null   float64
dtypes: float64(4), int64(10), object(3)
memory usage: 398.6+ KB

In [39]:
dflm.columns

Index(['ID', 'Semaine', 'Province', 'Pluviometrie_mm', 'Temperature_C', 'NDVI',
       'Humidite_pct', 'Densite_Population', 'Couverture_Vaccinale_pct',
       'Tests_Realises', 'Distance_Centre_Sante_km', 'Reservoirs_Animaux',
       'Mobilite_Humaine', 'Cas_Confirmes', 'Saison', 'Population_Risque',
       'Taux_Positivite_pct'],
      dtype='object')

In [40]:
df_txt = dflm.select_dtypes(include=["object"])
df_txt

             ID       Province Saison
0     OBS_00001        Mongala  Pluie
1     OBS_00002       Kinshasa  Seche
2     OBS_00003       Kinshasa  Seche
3     OBS_00004     Mai-Ndombe  Pluie
4     OBS_00005          Kasaï  Pluie
...         ...            ...    ...
2995  OBS_02996  Kongo Central  Pluie
2996  OBS_02997     Sud-Ubangi  Seche
2997  OBS_02998       Bas-Uele  Pluie
2998  OBS_02999      Haut-Uele  Pluie
2999  OBS_03000       Sud-Kivu  Pluie

[3000 rows x 3 columns]

In [41]:
df_txt.columns

Index(['ID', 'Province', 'Saison'], dtype='object')

In [42]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

columns = ['ID', 'Semaine', 'Province', 'Pluviometrie_mm', 'Temperature_C', 'NDVI',
       'Humidite_pct', 'Densite_Population', 'Couverture_Vaccinale_pct',
       'Tests_Realises', 'Distance_Centre_Sante_km', 'Reservoirs_Animaux',
       'Mobilite_Humaine', 'Cas_Confirmes', 'Saison', 'Population_Risque',
       'Taux_Positivite_pct']

for i in columns :
  dflm[i] = le.fit_transform(dflm[i])

In [43]:
dflm

,ID,Semaine,Province,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Saison,Population_Risque,Taux_Positivite_pct
0,0,0,16,204,64,353,24,34,255,6,21,1,3,29,0,735,616
1,1,1,8,54,57,347,34,102,186,21,4,1,5,42,1,806,426
2,2,2,8,57,72,206,22,135,473,22,15,0,7,20,1,1117,168
3,3,3,14,378,61,227,28,92,196,12,3,0,9,82,0,830,1139
4,4,4,5,125,18,176,21,81,240,17,23,1,5,24,0,2396,262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,2995,9,269,136,406,48,52,161,13,32,1,6,125,0,642,1437
2996,2996,2996,21,86,66,135,55,42,278,28,6,1,5,70,1,1452,601
2997,2997,2997,0,266,76,589,18,13,356,10,22,0,1,36,0,1271,603
2998,2998,2998,3,209,69,70,37,23,43,28,1,0,1,160,0,1111,1221
2999,2999,2999,20,124,90,504,17,46,599,15,45,1,1,10,0,2007,80

In [44]:
from sklearn.preprocessing import MinMaxScaler #Normzlisation

minmax = MinMaxScaler()
dflm_min = minmax.fit_transform(dflm)

dflm_scaler = pd.DataFrame(dflm_min, columns =dflm.columns)

dflm_scaler

,ID,Semaine,Province,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Cas_Confirmes,Saison,Population_Risque,Taux_Positivite_pct
0,0.000000,0.000000,0.64,0.536842,0.40000,0.547287,0.436364,0.085642,0.423588,0.111111,0.244186,1.0,0.333333,0.091483,0.0,0.285326,0.359184
1,0.000333,0.000333,0.32,0.142105,0.35625,0.537984,0.618182,0.256927,0.308970,0.388889,0.046512,1.0,0.555556,0.132492,1.0,0.312888,0.248397
2,0.000667,0.000667,0.32,0.150000,0.45000,0.319380,0.400000,0.340050,0.785714,0.407407,0.174419,0.0,0.777778,0.063091,1.0,0.433618,0.097959
3,0.001000,0.001000,0.56,0.994737,0.38125,0.351938,0.509091,0.231738,0.325581,0.222222,0.034884,0.0,1.000000,0.258675,0.0,0.322205,0.664140
4,0.001334,0.001334,0.20,0.328947,0.11250,0.272868,0.381818,0.204030,0.398671,0.314815,0.267442,1.0,0.555556,0.075710,0.0,0.930124,0.152770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.998666,0.998666,0.36,0.707895,0.85000,0.629457,0.872727,0.130982,0.267442,0.240741,0.372093,1.0,0.666667,0.394322,0.0,0.249224,0.837901
2996,0.999000,0.999000,0.84,0.226316,0.41250,0.209302,1.000000,0.105793,0.461794,0.518519,0.069767,1.0,0.555556,0.220820,1.0,0.563665,0.350437
2997,0.999333,0.999333,0.00,0.700000,0.47500,0.913178,0.327273,0.032746,0.591362,0.185185,0.255814,0.0,0.111111,0.113565,0.0,0.493401,0.351603
2998,0.999667,0.999667,0.12,0.550000,0.43125,0.108527,0.672727,0.057935,0.071429,0.518519,0.011628,0.0,0.111111,0.504732,0.0,0.431289,0.711953
2999,1.000000,1.000000,0.80,0.326316,0.56250,0.781395,0.309091,0.115869,0.995017,0.277778,0.523256,1.0,0.111111,0.031546,0.0,0.779115,0.046647

In [45]:
dflm_scaler.columns

Index(['ID', 'Semaine', 'Province', 'Pluviometrie_mm', 'Temperature_C', 'NDVI',
       'Humidite_pct', 'Densite_Population', 'Couverture_Vaccinale_pct',
       'Tests_Realises', 'Distance_Centre_Sante_km', 'Reservoirs_Animaux',
       'Mobilite_Humaine', 'Cas_Confirmes', 'Saison', 'Population_Risque',
       'Taux_Positivite_pct'],
      dtype='object')

In [70]:
X = df[
[
'Pluviometrie_mm',
'Temperature_C',
'NDVI',
'Humidite_pct',
'Densite_Population',
'Couverture_Vaccinale_pct',
'Tests_Realises',
'Distance_Centre_Sante_km',
'Reservoirs_Animaux',
'Mobilite_Humaine',
'Population_Risque'
]
]

y = df['Cas_Confirmes']

In [71]:
X.columns

Index(['Pluviometrie_mm', 'Temperature_C', 'NDVI', 'Humidite_pct',
       'Densite_Population', 'Couverture_Vaccinale_pct', 'Tests_Realises',
       'Distance_Centre_Sante_km', 'Reservoirs_Animaux', 'Mobilite_Humaine',
       'Population_Risque'],
      dtype='object')

In [72]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [73]:
x_train.columns

Index(['Pluviometrie_mm', 'Temperature_C', 'NDVI', 'Humidite_pct',
       'Densite_Population', 'Couverture_Vaccinale_pct', 'Tests_Realises',
       'Distance_Centre_Sante_km', 'Reservoirs_Animaux', 'Mobilite_Humaine',
       'Population_Risque'],
      dtype='object')

In [74]:
from sklearn.linear_model import LinearRegression

model_LRM = LinearRegression()

model_LRM.fit(x_train, y_train)

LinearRegression()

In [75]:
X

,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Population_Risque
0,206,24.4,0.480,64,39,31.8,150,22,1,4,3478
1,56,23.7,0.474,74,107,24.9,300,5,1,6,3713
2,59,25.2,0.333,62,140,53.9,310,16,0,8,4833
3,396,24.1,0.354,68,97,25.9,210,4,0,10,3777
4,127,19.8,0.303,61,86,30.3,260,24,1,6,9396
...,...,...,...,...,...,...,...,...,...,...,...
2995,271,31.6,0.534,88,57,22.4,220,33,1,7,3166
2996,88,24.6,0.262,95,47,34.1,370,7,1,6,6099
2997,268,25.6,0.720,58,18,41.9,190,23,0,2,5475
2998,211,24.9,0.196,77,28,10.6,370,2,0,2,4813
2999,126,27.0,0.632,57,51,74.3,240,46,1,2,8049

In [76]:
y

0        29
1        42
2        20
3        82
4        24
       ...
2995    125
2996     70
2997     36
2998    160
2999     10
Name: Cas_Confirmes, Length: 3000, dtype: int64

In [77]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [78]:
x_train.head()

,Pluviometrie_mm,Temperature_C,NDVI,Humidite_pct,Densite_Population,Couverture_Vaccinale_pct,Tests_Realises,Distance_Centre_Sante_km,Reservoirs_Animaux,Mobilite_Humaine,Population_Risque
642,57,34.0,0.654,78,49,31.2,150,11,0,3,1208
700,87,24.6,0.452,85,82,32.0,170,24,1,4,3802
226,44,27.0,0.572,60,95,47.2,280,2,0,7,3512
1697,400,20.8,0.247,73,56,46.4,280,3,1,6,5715
1010,86,32.6,0.140,95,281,64.3,100,45,0,3,3726

In [79]:
model_LRM = LinearRegression()
model_LRM.fit(x_train, y_train)

LinearRegression()

In [80]:
bo = model_LRM.intercept_
bo

-158.80451358948858

In [81]:
coef = model_LRM.coef_
coef

array([ 4.26707987e-01,  2.58633232e+00,  6.07833692e+01,  3.70218301e-01,
        1.42293299e-01, -1.72129907e+00,  3.61129019e-01, -8.18667168e-01,
       -2.61708028e+00, -6.14289996e-02,  1.71537742e-04])

In [82]:
y_pred = model_LRM.predict(x_test)
y_pred

array([ 55.39261643,  47.153626  , 230.62690851,  61.08648557,
        57.56641818, 163.6651768 , 170.56051607, 123.76798275,
        67.39646234,  17.22466669,  84.65021504, 104.3057245 ,
       -31.6513779 , 177.82409166,  68.17065481,  41.77683069,
       208.80917411,  92.26235451, 171.48089365,  82.05815694,
       220.82378771,  14.84469805,  52.47484215, 115.74664301,
       140.06751385,  53.78318494,  88.99097096, -14.03885501,
        40.76234874,  31.10671597, 109.58882329,  12.69966347,
        -4.86294759,  58.73270736, 170.03438291,  84.79055197,
        53.8541869 , 115.09393103, 170.01173714,  14.00388417,
       140.78661324, -16.56816846,  38.92360737, -27.38431597,
       -23.78853438,   4.84455652, 112.19367045,  26.64403409,
        43.37596568, 144.27103833, 122.76413332,  82.77965152,
       128.06090465,  46.00866867,   3.20844922,  32.32087352,
        50.16394887, 217.95204914, -40.77234868,  43.83842766,
       141.9339382 ,  49.69849616, 230.87625698,   3.38202517,
        17.90546924,  63.00992774,  50.02631487,  27.83957659,
       165.43790306,  20.75915466, 127.2049215 ,  41.77405879,
        54.76316104, 201.54704625,  24.67090141,  73.6851913 ,
        22.24514352,  20.35784373,  88.4532378 ,  60.94268727,
       119.80747773,  30.15628542, 155.98245987, 105.45408579,
       118.55721322,   2.83079435,  95.65828926,  46.73897069,
        21.64580717,  14.41074851,  34.77972523,  62.69995061,
        20.15052395,  47.51368225,  64.97010601, -57.55626403,
        79.48941358, 135.16959331,  84.48357651,  99.8965727 ,
       139.09165618, 108.78264909, 105.85220293,  60.26950134,
        88.75124185, 168.0409839 ,  37.25359908, 111.03206307,
        24.97997665,  69.05153143,  64.71508662, -36.6194476 ,
       113.49364071,  -9.0940359 , 152.99088968, -34.5212652 ,
        29.77844442, 140.30651487,  98.48509854,  25.14132183,
       -23.52577556,  75.8547296 , 149.68299545,  77.9863681 ,
         8.44927508, 172.02174901,  28.18204689,  65.60811705,
       -10.40496089,  32.85487862,  80.54958697,  35.93483913,
        -4.88213518, 153.60340393,  52.22020661,  47.48176138,
        43.21202581,  66.42113308,  79.29060608,  79.2969023 ,
       157.96373411,  62.0964094 , 159.03360669,  54.40668931,
       195.82876543,  15.91991651,  81.27755559,  23.86182429,
       137.72427041, 244.98359273,  60.82701397, 179.67898197,
       178.00236225,  97.12347015,  25.47555952, 200.88403302,
       179.79468402, 100.34380982, 134.71365438,  80.37278772,
        85.04718373,  46.28137279,  30.347077  ,  70.79888672,
        79.46806353, -67.55526019, 122.12500365,  84.06667994,
        25.28033389, 121.74915655,  75.10145429,  54.23352209,
       124.2366795 ,  72.89945028, 165.07908427, 168.37051763,
       128.51818572, 116.67891562, 146.83304688,  15.56086232,
         1.29910494, 173.37628766, 109.71425082, 108.02040839,
       178.02571683,  54.34477155,  36.32150383, 203.43175909,
        53.27661044,  59.51725872,  38.58141584,  10.43183084,
        63.35560094,  79.33241978, -37.30803673,  95.54471697,
       113.77859845, -34.52749117,  97.1478703 , 143.39053599,
        28.84809853,  72.3463076 , 103.20365549, 155.02946201,
        53.98140669, 225.57097912, 264.70844062, 185.0449023 ,
        99.18766075,  -7.26088698,  88.00580747,  91.3865371 ,
       148.0863225 , 109.87470743,  62.56607492,  29.02629358,
       148.32716138,  58.46622189,  73.9380688 , 138.10933876,
       132.56770138,  66.29006965, 269.24208359,  -8.7779111 ,
        37.40882974,  83.60703608,  50.76090271,  31.93236693,
        67.65946512, 104.03198675,  76.88522507, 128.9061934 ,
        86.18021888, 145.03085022, 178.69092281, 198.05631226,
        -4.55831351, 125.27119302,  81.33669414,  46.21730138,
         1.77587954,  53.30747126,  72.26424112, -31.76863901,
       248.68422086,  19.989498  ,  27.94476422,  64.90573272,
       153.26795026, 109.97024367, 149.84144762,  88.86490124,
         5.43287809,  36.78255159,  61.11563991,  33.59546841,
       227.11274043, 107.69031585,  70.58958752, 113.93845422,
       215.395013  , 119.49283949,  49.92585391,   9.68206942,
       172.29988346, 123.13156736,  -0.54664138,  79.4501956 ,
       -31.36436432, 152.95587082,  16.58735801,  69.84560609,
       181.34947351, 197.10551172,  60.33800645,  65.53860848,
       113.61775319, 154.00389015,  24.7872915 ,  60.30241122,
       108.25235304, 180.45532641,  39.760588  , 186.04859613,
        31.2174455 ,  87.10464798, -12.03738275, 124.63456912,
        86.17509951,  70.65915539,   7.5829548 , 137.91073393,
       125.42002855,  10.05894452,  39.28836018,  49.01066356,
        72.67816766,  39.89741771,  65.21638607,  36.85181094,
       174.11167909, 126.41584569,  33.01891304,  60.08686011,
       174.32932543, -15.1914971 ,  58.40711129, 158.19517334,
       131.8168454 ,  80.41631615, 189.75697966,  56.91225622,
        83.85702095, 116.64081621,  96.56667901,  92.36402344,
        22.81823613,  49.00422124, 180.3181729 , 153.55489089,
        22.23525891, 110.6168127 , 220.06307943, 123.41141695,
       152.42986284, 178.59969771, 118.93963485,  57.96962661,
        77.6860424 ,  97.5505134 , -45.25687007, 147.00908985,
       131.38224727, 167.00902555,  67.12556669,   8.76604482,
       137.8373339 , 123.1028347 , 156.39087358,  77.68139029,
        27.1885444 ,  67.48147668, 142.86027296,  88.51694879,
       133.37700735,  67.86063646,  -1.99087258,  73.2327303 ,
       113.94707978, 115.86280624,  16.15086871, 225.1016374 ,
       124.88300878, 104.56544836,  93.46812348, 178.76003842,
        58.80401906,  20.92343729, 124.82814274,  82.91165737,
        18.47608923,  98.02906603,  51.57210965,  40.97101259,
       116.99000532,  85.73890489,  76.69963354,  90.94793755,
       113.59425139,  29.60544868,  63.47542066,  62.11704011,
        88.19115375,  53.06980406, -58.47317517, 106.84936303,
       137.33018769,  55.8678505 ,  65.51131795,  19.86712042,
       147.84788359,  92.36061681, 130.3675267 ,  77.72148859,
       111.17134802,  16.21950027,  60.22714537, 115.1766292 ,
       -49.19484394, 120.44410796,  32.77461973,  22.81504578,
        70.89238935,  80.5009451 ,  95.43420402,  42.99471519,
        56.58301186, -75.22399009,  70.10351978,  67.40465391,
        27.36240318, 179.95864306, -29.31586789,  74.77596266,
       124.92592442,  82.14284082,  70.35383676, 189.54780511,
        50.70806778, 132.14333678,  10.63298225, 141.17473091,
        51.41143512,  73.69781165,  54.71387848, 208.99806193,
       142.36350367, 116.99323055, 146.06810561, 146.17285525,
       163.42849377,  52.86384782,  50.40577704,  90.3915285 ,
       170.65320481,  53.72520879,  29.41866853,  92.34942153,
       204.79128599, 134.89695492,  59.92906309, 116.80942599,
       -13.53203704,   1.14365293, -44.53106279, 149.35562804,
        77.80028334, 181.95774467,  42.84974767, -36.54878888,
         9.72727347,  79.25177915, 139.31252561, 107.76743462,
        40.46510284, -14.7600718 ,  99.95720689, 104.64045111,
       117.01844198,   4.03403346,  29.99661309, 127.76919257,
       294.69285407, 116.81524479,  51.48067768,  60.50393997,
        15.76173941, 103.54738246,  66.62911227, 271.6782678 ,
        82.50660891, 147.18661812, -43.54971023,  41.38674927,
        72.11449613,  33.57395638, 163.5908193 ,   8.9993305 ,
         7.01984593,  83.54975732,  -2.36013177,  16.56341681,
        23.19340671,  57.09012029, 129.69123982,  47.51026136,
        22.48341   , 178.08327039, 229.51227389,  65.08200812,
       154.07382761,  43.16900872,  25.04099151, 123.20144831,
        73.2411107 ,  55.42701825, 140.1888504 , 142.39284472,
        36.95989409, 115.85169222, 158.86626311,  -4.41278987,
       139.23659402,  98.56419183, 141.9058067 ,  35.3397759 ,
       -11.87145803, 104.98374721,  99.42013573,  59.46031419,
        56.03962866,  39.97248432,  90.14477517,  78.87909539,
       155.5147521 , 133.92098351,  53.01147269,  92.02255183,
        78.01640537, 106.95637296, 142.98900607,  85.74202697,
        27.01495783, 196.84396693, -50.56794203, 200.52342608,
        92.90028658, 211.44462786,   2.01424475,  25.32029226,
       127.9228797 ,   5.55542313, 175.66610625, 138.28448146,
        88.11137335,  59.21742277, -48.6733206 ,  43.00645506,
        30.9597117 ,  36.20075234,  39.07790883, 250.99878644,
       160.78272954,  98.2418517 ,  63.45275917,   8.30312979,
       -58.32575644,  97.26245776,  -1.83544785, 128.42416762,
       175.18396082,  -2.23690379,  17.517982  ,   8.04651383,
       -10.77438442,  57.40102846,   5.0056115 ,  12.47686642,
        46.90489183, 115.63682987, 162.93243981,  90.78090453,
        58.04334052,  13.52796209,  61.3083747 , 133.96863601,
        88.88233028,   5.21181795, 172.75457491,  69.62795036,
       209.90932113,  50.75995191, 224.19892275,  39.03527429,
        74.63165491, 119.52623305,  67.50793241,  66.22434656,
        55.02739475,  42.68055712,  -4.82383228, 149.71912417,
       -39.71521449,  11.10633703, 115.40242667,  52.7983126 ,
        25.26256948,  40.96952196, 172.8140337 ,  71.08289374,
       111.46766382,  88.557542  ,  58.76776087, 202.42221984,
        52.29534236,  37.00836848,  42.74567323,  22.00594704,
        -1.44927845,  52.60410483,  18.80426122,  87.46541453,
       166.01145959,   3.09646885, 134.53147335,  82.99483478,
         2.10558887,  49.09164618,  18.97027949,  68.98023945])

In [85]:
print("MSE",mean_squared_error(y_test, y_pred))
print("MAE",mean_absolute_error(y_test, y_pred))
#print("RMSE",math.sqrt(mean_squared_error(y_test, y_pred)))
print("R2", r2_score(y_test, y_pred) )
import numpy as np

RMSE = np.sqrt(934.4263713044616)

print(RMSE)

MSE 934.4263713044616
MAE 22.15925704522021
R2 0.8255457645747558
30.568388431588303

In [86]:
model_LRM.coef_

array([ 4.26707987e-01,  2.58633232e+00,  6.07833692e+01,  3.70218301e-01,
        1.42293299e-01, -1.72129907e+00,  3.61129019e-01, -8.18667168e-01,
       -2.61708028e+00, -6.14289996e-02,  1.71537742e-04])

In [87]:
pd.DataFrame({
    "Variable": X.columns,
    "Coefficient": model_LRM.coef_
})

                    Variable  Coefficient
0            Pluviometrie_mm     0.426708
1              Temperature_C     2.586332
2                       NDVI    60.783369
3               Humidite_pct     0.370218
4         Densite_Population     0.142293
5   Couverture_Vaccinale_pct    -1.721299
6             Tests_Realises     0.361129
7   Distance_Centre_Sante_km    -0.818667
8         Reservoirs_Animaux    -2.617080
9           Mobilite_Humaine    -0.061429
10         Population_Risque     0.000172

In [88]:
import statsmodels.api as sm

X_sm = sm.add_constant(X)

model_sm = sm.OLS(y, X_sm).fit()

print(model_sm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          Cas_Confirmes   R-squared:                       0.822
Model:                            OLS   Adj. R-squared:                  0.822
Method:                 Least Squares   F-statistic:                     1256.
Date:                Mon, 20 Jul 2026   Prob (F-statistic):               0.00
Time:                        22:24:11   Log-Likelihood:                -14416.
No. Observations:                3000   AIC:                         2.886e+04
Df Residuals:                    2988   BIC:                         2.893e+04
Df Model:                          11
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                     -158.4617      5.952    -26.624      0.000    -170.132    -146.792
Pluviometrie_mm              0.4288      0.005     80.673      0.000       0.418       0.439
Temperature_C                2.4715      0.141     17.487      0.000       2.194       2.749
NDVI                        60.0950      3.437     17.485      0.000      53.356      66.834
Humidite_pct                 0.3854      0.047      8.273      0.000       0.294       0.477
Densite_Population           0.1493      0.006     26.229      0.000       0.138       0.160
Couverture_Vaccinale_pct    -1.7354      0.039    -45.071      0.000      -1.811      -1.660
Tests_Realises               0.3674      0.006     59.809      0.000       0.355       0.379
Distance_Centre_Sante_km    -0.7939      0.036    -22.174      0.000      -0.864      -0.724
Reservoirs_Animaux          -2.1146      1.105     -1.913      0.056      -4.281       0.052
Mobilite_Humaine            -0.1628      0.277     -0.588      0.557      -0.706       0.380
Population_Risque         5.939e-05      0.000      0.289      0.773      -0.000       0.000
==============================================================================
Omnibus:                      590.956   Durbin-Watson:                   1.967
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1569.367
Skew:                           1.051   Prob(JB):                         0.00
Kurtosis:                       5.852   Cond. No.                     6.81e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.81e+04. This might indicate that there are
strong multicollinearity or other numerical problems.